# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-11-25 09:01+0330\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: config/models.py:17
msgid "There is can be only one config instance"
msgstr "شما فقط میتوانید یک تنظیمات داشته باشید"

#: config/serializers.py:43
msgid "You are not permitted to set global config with PUT method"
msgstr "امکان آپدیت کانفیگ به صورت سراسری وجود ندارد"

#: daas/settings.py:157
msgid "Farsi"
msgstr "قارسی"

#: daas/settings.py:158
msgid "English"
msgstr "انگلیسی"

#: services/desktop.py:186
#, fuzzy
#| msgid "invalid data passed"
msgid "invalid daas"
msgstr "کاربر معتبر نیست"

#: users/models.py:59
msgid "you don't have meta configuration"
msgstr "شما هنوز کانفیگی ایجاد تکرده اید"

#: users/views.py:52
msgid "your account is locked!"
msgstr "دسکتاپ شما مسدود شده است.با ادمین تماس بگیرید."

#: users/views.py:63
msgid "you reach your time limit!"
msgstr "زمان استفاده شما از حد مجاز گذشته است"

#: users/views.py:80
msgid "invalid user"
msgstr "کاربر معتبر نیست"

#: users/views.py:88 users/views.py:126
msgid "successfull"
msgstr "موفق"

#: users/views.py:90
msgid "you are not admin"
msgstr "شما ادمین نیستید"

#: users/views.py:93
msgid "invalid username or password"
msgstr "ایمیل یا پسورد اشتباه است"

#: users/views.py:131 users/views.py:153
msgid "invalid data passed"
msgstr "کاربر معتبر نیست"

#: users/views.py:172
msgid "successfully update"
msgstr "با موفقیت به روز رسانی شد"

#: users/views.py:174
msgid "you can't update usage of down desktop!"
msgstr "این دسکتاپ فعال نیست"

#: users/views.py:177 users/views.py:219
msgid "internal server error"
msgstr "خطای داخلی"

#: users/views.py:193 users/views.py:200
msgid "reset successfully"
msgstr "با موفقیت به روز رسانی شد"

#: users/views.py:240
#, fuzzy
#| msgid "reset successfully"
msgid "locked account successfully"
msgstr "با موفقیت به روز رسانی شد"

#: users/views.py:243
msgid "can't lock account with given id"
msgstr "شما نمیتوانید با آیدی امانت را لاک کنید"

#~ msgid "can not connect to file server"
#~ msgstr "اتصال به فایل سرور امکان پذبر نمی باشد"

#, fuzzy
#~| msgid "invalid data passed"
#~ msgid "invalid_data_passed"
#~ msgstr "کاربر معتبر نیست"
